Nationality = input("enter a nationality: ")
YEAR = input("enter a Year: ")
Noun1 = input("enter a noun:")
Noun2 = input("enter a noun: ")
Noun3 = input("enter a noun: ")
Adjective = input("enter a Adjective: ")
verb = input("enter a verb: ")
PLNoun = input("enter a plural noun: ")

print("Pizza was invented by a " + Nationality +  " man in" + YEAR + ". To make pizza, You must combine one" + Noun1 + "and" + Noun2 +  ". Pizza is enjoyed by" + PLNoun + "Another good food is " + Noun3 + "." + Noun3 + "is very" + Adjective + ". I" + verb + "food.")