Nationality = input("Enter a nationality: ")
YEAR = input("Enter a Year: ")
Noun1 = input("Enter a noun:")
Noun2 = input("Enter a noun: ")
Noun3 = input("Enter a noun: ")
Adjective = input("Enter an adjective: ")
verb = input("Enter a verb: ")
PLNoun = input("Enter a plural noun: ")

print("Pizza was invented by a " + Nationality +  " man in " + YEAR + ". To make pizza, You must combine one " + Noun1 + " and " + Noun2 +  ". Pizza is enjoyed by " + PLNoun + ". Another good food is " + Noun3 + ". " + Noun3 + " is very " + Adjective + ". I " + verb + " food.")